## 1.

In [2]:
import numpy as np
list_ = [ '1' ,'2' ,'3', '4', '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [4]:
list_

['1', '2', '3', '4', '5']

In [5]:
type(array_list)

numpy.ndarray

In [6]:
type(list_)

list

## 2

In [10]:
for a in list_:
    print( f"list element {a}  and its datatype: {type(a)}")
for b in array_list:
    print( f"array_list element {b}  and its datatype: {type(b)}")

list element 1  and its datatype: <class 'str'>
list element 2  and its datatype: <class 'str'>
list element 3  and its datatype: <class 'str'>
list element 4  and its datatype: <class 'str'>
list element 5  and its datatype: <class 'str'>
array_list element 1  and its datatype: <class 'numpy.str_'>
array_list element 2  and its datatype: <class 'numpy.str_'>
array_list element 3  and its datatype: <class 'numpy.str_'>
array_list element 4  and its datatype: <class 'numpy.str_'>
array_list element 5  and its datatype: <class 'numpy.str_'>


## 3.

In [11]:
array_list = np.array(object = list_, dtype = int)

In [12]:
array_list

array([1, 2, 3, 4, 5])

In [13]:
for a in list_:
    print( f"list element {a}  and its datatype: {type(a)}")
for b in array_list:
    print( f"array_list element {b}  and its datatype: {type(b)}")

list element 1  and its datatype: <class 'str'>
list element 2  and its datatype: <class 'str'>
list element 3  and its datatype: <class 'str'>
list element 4  and its datatype: <class 'str'>
list element 5  and its datatype: <class 'str'>
array_list element 1  and its datatype: <class 'numpy.int32'>
array_list element 2  and its datatype: <class 'numpy.int32'>
array_list element 3  and its datatype: <class 'numpy.int32'>
array_list element 4  and its datatype: <class 'numpy.int32'>
array_list element 5  and its datatype: <class 'numpy.int32'>


    Yes , there is difference between the datatypes of the list_ and array_list variable.


## 4.

In [15]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

## (i)

In [16]:
num_array.shape

(2, 3)

## (ii)

In [17]:
num_array.size

6

## 5.

In [22]:
arr = np.zeros((3,3) , "int")

In [23]:
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## 6.

In [28]:
arr2 = np.eye(5,dtype = "int")

In [29]:
arr2

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])